"""Add idempotency_key to transactions

Revision ID: b026ad1f6b72
Revises: 36eef077a3d6
Create Date: 2025-07-04 14:17:31.370962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b026ad1f6b72'
down_revision: Union[str, Sequence[str], None] = '36eef077a3d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add the column with a server default (e.g., empty string or a placeholder UUID)
    op.add_column('transactions', sa.Column('idempotency_key', sa.String(), nullable=False, server_default='default-key'))
    # 2. Remove the server default (optional, but recommended for future inserts)
    op.alter_column('transactions', 'idempotency_key', server_default=None)
    # 3. Add the unique constraint
    op.create_unique_constraint(
        'uq_user_idempotency',
        'transactions',
        ['user_id', 'idempotency_key']
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_idempotency', 'transactions', type_='unique')
    op.drop_column('transactions', 'idempotency_key')
    # ### end Alembic commands ###
