"""Add type column to transactions

Revision ID: c0b0c7db76ef
Revises: b026ad1f6b72
Create Date: 2025-07-05 10:29:15.603957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0b0c7db76ef'
down_revision: Union[str, Sequence[str], None] = 'b026ad1f6b72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    transaction_type_enum = sa.Enum('income', 'expense', name='transactiontype')
    transaction_type_enum.create(op.get_bind())
    
    op.add_column('transactions', sa.Column('type', transaction_type_enum, nullable=True))
    
    connection = op.get_bind()
    connection.execute(
        sa.text("UPDATE transactions SET type = 'expense' WHERE type IS NULL")
    )
    
    op.alter_column('transactions', 'type', nullable=False)
    
    op.create_index(op.f('ix_transactions_type'), 'transactions', ['type'], unique=False)

    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_type'), table_name='transactions')
    op.drop_column('transactions', 'type')
    # ### end Alembic commands ###
